services:
  - type: web
    name: botdiscord
    runtime: python
    buildCommand: |
      pip uninstall -y discord discord.py py-cord
      pip cache purge
      pip install -U --force-reinstall py-cord==2.3.2
      pip list
      pip show py-cord
      pip freeze > installed.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
