services:
  - type: web
    name: botdiscord
    runtime: python
    buildCommand: |
      pip uninstall -y discord discord.py py-cord
      pip install -U --force-reinstall git+https://github.com/Pycord-Development/pycord.git@main
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
