build:
  installPackages:
    - pip uninstall -y discord discord.py
    - pip install py-cord==2.4.1

services :
  - type : web
    name : botdiscord
    runtime : python
    buildCommand : "pip install -r requirements.txt"
    startCommand : "python main.py"
    envVars :
      - key : PYTHON_VERSION
        value : 3.10.11
