services:
  - type: web
    name: botdiscord
    runtime: python
    buildCommand: |
      pip uninstall -y discord discord.py py-cord
      pip install --no-cache-dir -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
